### ISSUE TITLE
Error: Unable to access jarfile EarthdawnCharacterEditor.jar

### ISSUE THREAD

**Issue by new-gen23** [lortas/Earthdawn-Character-Editor#3]
The jar file is missing. I assume I have to compile it? But I can't find a tutorial or command, how to compile it.

**Comment by new-gen23** [comment]
Solution:
ant compile
ant jar

**Comment by new-gen23** [comment]
Ok, I copied the jar file from Earthdawn-Character-Editor/temp/jar/EarthdawnCharacterEditor.jar to  Earthdawn-Character-Editor/cmd. 
Now, it failed because the config folder was missing. So I copied the config folder also to  Earthdawn-Character-Editor. Now, it throws me the error:
Exception in thread "main" java.lang.NoClassDefFoundError: com/itextpdf/text/DocumentException
	at de.earthdawn.EarthdawnCharacterEditor.main(EarthdawnCharacterEditor.java:71)
Caused by: java.lang.ClassNotFoundException: com.itextpdf.text.DocumentException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by lortas** [comment]
jar file will now be compiled into root folder.

To run ECE, just use the new ant target "run".
